_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 55
            "4": 3.12.10
            "5": 0.20.1
            "12": 0.20.1
            "13": darwin-x86_64
