_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
                - 55
            "4": 3.12.10
            "5": 0.20.1
            "12": 0.20.1
            "13": darwin-x86_64
batch_size:
    value: 32
embedding_dim:
    value: 100
learning_rate:
    value: 0.001
margin:
    value: 0.1
num_epochs:
    value: 10
