_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.17
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
                - 55
            "4": 3.10.17
            "5": 0.20.1
            "12": 0.20.1
            "13": darwin-arm64
batch_size:
    value: 512
embedding_dim:
    value: 100
learning_rate:
    value: 0.003
loss_margin:
    value: 0.3
num_epochs:
    value: 10
